package org.mskcc.cbio.oncokb.model.impl;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA

import org.mskcc.cbio.oncokb.model.TumorType;



/**
 * TumorTypeImpl generated by hbm2java
 */
public class TumorTypeImpl  implements java.io.Serializable, TumorType {


     private String tumorTypeId;
     private String name;
     private String shortName;
     private String color;

    public TumorTypeImpl() {
    }

	
    public TumorTypeImpl(String tumorTypeId, String name, String shortName) {
        this.tumorTypeId = tumorTypeId;
        this.name = name;
        this.shortName = shortName;
    }
    public TumorTypeImpl(String tumorTypeId, String name, String shortName, String color) {
       this.tumorTypeId = tumorTypeId;
       this.name = name;
       this.shortName = shortName;
       this.color = color;
    }
   
    @Override
    public String getTumorTypeId() {
        return this.tumorTypeId;
    }
    
    @Override
    public void setTumorTypeId(String tumorTypeId) {
        this.tumorTypeId = tumorTypeId;
    }
    @Override
    public String getName() {
        return this.name;
    }
    
    @Override
    public void setName(String name) {
        this.name = name;
    }
    @Override
    public String getShortName() {
        return this.shortName;
    }
    
    @Override
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    @Override
    public String getColor() {
        return this.color;
    }
    
    @Override
    public void setColor(String color) {
        this.color = color;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.tumorTypeId != null ? this.tumorTypeId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TumorTypeImpl other = (TumorTypeImpl) obj;
        if ((this.tumorTypeId == null) ? (other.tumorTypeId != null) : !this.tumorTypeId.equals(other.tumorTypeId)) {
            return false;
        }
        return true;
    }


}


