-- NOTE THAT THE DATABASE SCHEMA IS AUTOMATICALLY GENERATED BY HIBERNATE
-- THE ONLY PERPOSE OF THIS FILE IS PROVIDE A REFERENCE. IT MAY NOT BE UPDATED
-- TO THE LATEST CODE.

-- phpMyAdmin SQL Dump
-- version 3.4.3.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 13, 2014 at 05:50 PM
-- Server version: 5.1.58
-- PHP Version: 5.3.26

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `oncokb`
--

-- --------------------------------------------------------

--
-- Table structure for table `alteration`
--

CREATE TABLE IF NOT EXISTS `alteration` (
  `alteration_id` int(11) NOT NULL AUTO_INCREMENT,
  `entrez_gene_id` int(11) NOT NULL,
  `alteration` varchar(30) NOT NULL COMMENT 'V600E, truncating, AMP, DEL',
  `type` varchar(10) NOT NULL COMMENT 'Mutation, CNA',
  PRIMARY KEY (`alteration_id`),
  KEY `FKD5A6189FC602BC92` (`entrez_gene_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=26 ;

-- --------------------------------------------------------

--
-- Table structure for table `drug`
--

CREATE TABLE IF NOT EXISTS `drug` (
  `drug_id` int(11) NOT NULL AUTO_INCREMENT,
  `drug_name` varchar(255) NOT NULL,
  `synonyms` text,
  `fda_approved` bit(1) NOT NULL,
  PRIMARY KEY (`drug_id`),
  UNIQUE KEY `drug_name` (`drug_name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `evidence`
--

CREATE TABLE IF NOT EXISTS `evidence` (
  `evidence_id` int(11) NOT NULL AUTO_INCREMENT,
  `evidence_type` varchar(255) DEFAULT NULL,
  `tumor_type_id` varchar(25) DEFAULT NULL,
  `drug_id` int(11) DEFAULT NULL,
  `alteration_id` int(11) NOT NULL,
  `known_effect` varchar(255) DEFAULT NULL,
  `description_of_known_effect` text,
  `context` text COMMENT 'coregulated events',
  PRIMARY KEY (`evidence_id`),
  KEY `FK16D39E5738F6863E` (`tumor_type_id`),
  KEY `FK16D39E5744975E15` (`drug_id`),
  KEY `FK16D39E57AAD5975` (`alteration_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=26 ;

-- --------------------------------------------------------

--
-- Table structure for table `gene`
--

CREATE TABLE IF NOT EXISTS `gene` (
  `entrez_gene_id` int(11) NOT NULL,
  `hugo_symbol` varchar(50) NOT NULL,
  `name` text NOT NULL,
  `summary` text,
  PRIMARY KEY (`entrez_gene_id`),
  UNIQUE KEY `hugo_symbol` (`hugo_symbol`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `gene_alias`
--

CREATE TABLE IF NOT EXISTS `gene_alias` (
  `entrez_gene_id` int(11) NOT NULL,
  `alias` varchar(255) DEFAULT NULL,
  KEY `FKF1C8F0A6C602BC92` (`entrez_gene_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `gene_label`
--

CREATE TABLE IF NOT EXISTS `gene_label` (
  `entrez_gene_id` int(11) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  KEY `FKF25ED94AC602BC92` (`entrez_gene_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `literature`
--

CREATE TABLE IF NOT EXISTS `literature` (
  `evidence_id` int(11) NOT NULL,
  `pmid` varchar(255) DEFAULT NULL,
  KEY `FK9800D551F7262935` (`evidence_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `tumor_type`
--

CREATE TABLE IF NOT EXISTS `tumor_type` (
  `tumor_type_id` varchar(25) NOT NULL,
  `name` varchar(255) NOT NULL,
  `short_name` varchar(25) NOT NULL,
  `color` varchar(31) DEFAULT NULL,
  PRIMARY KEY (`tumor_type_id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `short_name` (`short_name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
