package org.mskcc.cbio.oncokb.model;


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.List;
import java.util.Set;
import java.util.logging.Level;


/**
 * TumorType generated by hbm2java
 */
public class EvidenceQueries implements java.io.Serializable {
    private List<Query> queries; //Optional, This id is passed from request. The identifier used to distinguish the query
    @JsonIgnore
    private String geneStatus;
    private String evidenceTypes;
    private Set<LevelOfEvidence> levels;
    private String source;
    private Boolean highestLevelOnly;

    public EvidenceQueries() {
    }

    public List<Query> getQueries() {
        return queries;
    }

    public void setQueries(List<Query> queries) {
        this.queries = queries;
    }

    public String getGeneStatus() {
        return geneStatus;
    }

    public void setGeneStatus(String geneStatus) {
        this.geneStatus = geneStatus;
    }

    public String getEvidenceTypes() {
        return evidenceTypes;
    }

    public void setEvidenceTypes(String evidenceTypes) {
        this.evidenceTypes = evidenceTypes;
    }

    public Set<LevelOfEvidence> getLevels() {
        return levels;
    }

    public void setLevels(Set<LevelOfEvidence> levels) {
        this.levels = levels;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Boolean getHighestLevelOnly() {
        return highestLevelOnly;
    }

    public void setHighestLevelOnly(Boolean highestLevelOnly) {
        this.highestLevelOnly = highestLevelOnly;
    }
}


