package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA

import java.util.List;


/**
 * TumorType generated by hbm2java
 */
public class EvidenceQueries implements java.io.Serializable {
    private List<EvidenceQuery> queries; //Optional, This id is passed from request. The identifier used to distinguish the query
    private String geneStatus;
    private String evidenceTypes;
    private String source;

    public EvidenceQueries() {
    }

    public List<EvidenceQuery> getQueries() {
        return queries;
    }

    public void setQueries(List<EvidenceQuery> queries) {
        this.queries = queries;
    }

    public String getGeneStatus() {
        return geneStatus;
    }

    public void setGeneStatus(String geneStatus) {
        this.geneStatus = geneStatus;
    }

    public String getEvidenceTypes() {
        return evidenceTypes;
    }

    public void setEvidenceTypes(String evidenceTypes) {
        this.evidenceTypes = evidenceTypes;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }
}


