package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;



/**
 * Evidence generated by hbm2java
 */
public class Evidence implements java.io.Serializable {


    private Integer evidenceId;
    private EvidenceBlob EvidenceBlob;
    private Set<Drug> drugs;
    private String knownEffect;
    private LevelOfEvidence levelOfEvidence;
    private Set<Article> articles;
    private Set<NccnGuideline> nccnGuidelines = new HashSet<NccnGuideline>(0);
    private Set<ClinicalTrial> clinicalTrials = new HashSet<ClinicalTrial>(0);

    public Evidence() {
    }
    
    public Evidence(EvidenceBlob EvidenceBlob, Set<Drug> drugs, String knownEffect, LevelOfEvidence levelOfEvidence, Set<Article> articles, Set<NccnGuideline> nccnGuidelines, Set<ClinicalTrial> clinicalTrials) {
        this.drugs = drugs;
        this.knownEffect = knownEffect;
        this.levelOfEvidence = levelOfEvidence;
        this.articles = articles;
        this.nccnGuidelines = nccnGuidelines;
        this.clinicalTrials = clinicalTrials;
    }
   
    public Integer getEvidenceId() {
        return this.evidenceId;
    }
    
    
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }

    public EvidenceBlob getEvidenceBlob() {
        return EvidenceBlob;
    }

    public void setEvidenceBlob(EvidenceBlob EvidenceBlob) {
        this.EvidenceBlob = EvidenceBlob;
    }

    public LevelOfEvidence getLevelOfEvidence() {
        return levelOfEvidence;
    }

    public void setLevelOfEvidence(LevelOfEvidence levelOfEvidence) {
        this.levelOfEvidence = levelOfEvidence;
    }

    public Set<Drug> getDrugs() {
        return drugs;
    }

    public void setDrugs(Set<Drug> drugs) {
        this.drugs = drugs;
    }
    
    public String getKnownEffect() {
        return this.knownEffect;
    }
    
    
    public void setKnownEffect(String knownEffect) {
        this.knownEffect = knownEffect;
    }

    public Set<Article> getArticles() {
        return articles;
    }

    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    
    public Set<NccnGuideline> getNccnGuidelines() {
        return this.nccnGuidelines;
    }
    
    public void setNccnGuidelines(Set<NccnGuideline> nccnGuidelines) {
        this.nccnGuidelines = nccnGuidelines;
    }

    public Set<ClinicalTrial> getClinicalTrials() {
        return clinicalTrials;
    }

    public void setClinicalTrials(Set<ClinicalTrial> clinicalTrials) {
        this.clinicalTrials = clinicalTrials;
    }
}


