package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TumorType generated by hbm2java
 */

public class IndicatorQueryTreatment implements java.io.Serializable {
    private Set<Drug> drugs = new HashSet<Drug>(0);
    private Set<String> approvedIndications = new HashSet<String>(0);
    private Boolean fdaApproved;
    private LevelOfEvidence level;
    private Set<String> pmids = new HashSet<String>(0);
    private Set<String> abstracts = new HashSet<String>(0);

    public IndicatorQueryTreatment() {
    }

    public Set<Drug> getDrugs() {
        return drugs;
    }

    public void setDrugs(Set<Drug> drugs) {
        this.drugs = drugs;
    }

    public Set<String> getApprovedIndications() {
        return approvedIndications;
    }

    public void setApprovedIndications(Set<String> approvedIndications) {
        this.approvedIndications = approvedIndications;
    }

    public Boolean getFdaApproved() {
        return fdaApproved;
    }

    public void setFdaApproved(Boolean fdaApproved) {
        this.fdaApproved = fdaApproved;
    }

    public LevelOfEvidence getLevel() {
        return level;
    }

    public void setLevel(LevelOfEvidence level) {
        this.level = level;
    }

    public Set<String> getPmids() {
        return pmids;
    }

    public void setPmids(Set<String> pmids) {
        this.pmids = pmids;
    }

    public Set<String> getAbstracts() {
        return abstracts;
    }

    public void setAbstracts(Set<String> abstracts) {
        this.abstracts = abstracts;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof IndicatorQueryTreatment)) return false;

        IndicatorQueryTreatment treatment = (IndicatorQueryTreatment) o;

        if (getDrugs() != null ? !getDrugs().equals(treatment.getDrugs()) : treatment.getDrugs() != null) return false;
        if (getApprovedIndications() != null ? !getApprovedIndications().equals(treatment.getApprovedIndications()) : treatment.getApprovedIndications() != null)
            return false;
        if (getFdaApproved() != null ? !getFdaApproved().equals(treatment.getFdaApproved()) : treatment.getFdaApproved() != null)
            return false;
        if (getLevel() != treatment.getLevel()) return false;
        if (getPmids() != null ? !getPmids().equals(treatment.getPmids()) : treatment.getPmids() != null) return false;
        return getAbstracts() != null ? getAbstracts().equals(treatment.getAbstracts()) : treatment.getAbstracts() == null;

    }

    @Override
    public int hashCode() {
        int result = getDrugs() != null ? getDrugs().hashCode() : 0;
        result = 31 * result + (getApprovedIndications() != null ? getApprovedIndications().hashCode() : 0);
        result = 31 * result + (getFdaApproved() != null ? getFdaApproved().hashCode() : 0);
        result = 31 * result + (getLevel() != null ? getLevel().hashCode() : 0);
        result = 31 * result + (getPmids() != null ? getPmids().hashCode() : 0);
        result = 31 * result + (getAbstracts() != null ? getAbstracts().hashCode() : 0);
        return result;
    }
}


