package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TumorType generated by hbm2java
 */

public class IndicatorQueryTreatment implements java.io.Serializable {
    private Set<Drug> drugs = new HashSet<Drug>(0);
    private Set<String> approvedIndications = new HashSet<String>(0);
    private Boolean fdaApproved;
    private LevelOfEvidence level;
    private Set<String> pmids = new HashSet<String>(0);
    private Set<ArticleAbstract> abstracts = new HashSet<ArticleAbstract>(0);

    public IndicatorQueryTreatment() {
    }

    public Set<Drug> getDrugs() {
        return drugs;
    }

    public void setDrugs(Set<Drug> drugs) {
        this.drugs = drugs;
    }

    public Set<String> getApprovedIndications() {
        return approvedIndications;
    }

    public void setApprovedIndications(Set<String> approvedIndications) {
        this.approvedIndications = approvedIndications;
    }

    public Boolean getFdaApproved() {
        return fdaApproved;
    }

    public void setFdaApproved(Boolean fdaApproved) {
        this.fdaApproved = fdaApproved;
    }

    public LevelOfEvidence getLevel() {
        return level;
    }

    public void setLevel(LevelOfEvidence level) {
        this.level = level;
    }

    public Set<String> getPmids() {
        return pmids;
    }

    public void setPmids(Set<String> pmids) {
        this.pmids = pmids;
    }

    public Set<ArticleAbstract> getAbstracts() {
        return abstracts;
    }

    public void setAbstracts(Set<ArticleAbstract> abstracts) {
        this.abstracts = abstracts;
    }
}


