package org.mskcc.cbio.oncokb.model;


import com.fasterxml.jackson.annotation.JsonIgnore;
import org.apache.commons.lang3.StringUtils;
import org.mskcc.cbio.oncokb.apiModels.annotation.*;
import org.mskcc.cbio.oncokb.genomenexus.GNVariantAnnotationType;
import org.mskcc.cbio.oncokb.util.AlterationUtils;
import org.mskcc.cbio.oncokb.util.GeneUtils;
import org.mskcc.cbio.oncokb.util.QueryUtils;

import java.util.ArrayList;
import java.util.List;

import static org.mskcc.cbio.oncokb.Constants.DEFAULT_REFERENCE_GENOME;
import static org.mskcc.cbio.oncokb.util.GeneAnnotator.findGene;


/**
 * TumorType generated by hbm2java
 */
public class Query implements java.io.Serializable {
    private String id; //Optional, This id is passed from request. The identifier used to distinguish the query
    private ReferenceGenome referenceGenome = DEFAULT_REFERENCE_GENOME;
    private String type; // Query type. Different type may return different result.
    private String hugoSymbol;
    private Integer entrezGeneId;
    private String alteration;
    private String alterationType;
    private StructuralVariantType svType;
    private String tumorType;
    private String consequence;
    private Integer proteinStart;
    private Integer proteinEnd;
    private String hgvs;

    public Query() {
    }

    public Query(AnnotateMutationByProteinChangeQuery mutationQuery) {
        this.id = mutationQuery.getId();
        this.type = AnnotationQueryType.REGULAR.getName();
        this.setTumorType(mutationQuery.getTumorType());

        if (mutationQuery.getGene() != null) {
            this.hugoSymbol = mutationQuery.getGene().getHugoSymbol();
            this.entrezGeneId = mutationQuery.getGene().getEntrezGeneId();
        }

        setAlteration(mutationQuery.getAlteration());
        this.consequence = mutationQuery.getConsequence();
        this.proteinStart = mutationQuery.getProteinStart();
        this.proteinEnd = mutationQuery.getProteinEnd();
        this.referenceGenome = mutationQuery.getReferenceGenome();
        if (this.referenceGenome == null) {
            this.referenceGenome = DEFAULT_REFERENCE_GENOME;
        }
    }

    public Query(AnnotateMutationByHGVSgQuery mutationQuery) {
        this.id = mutationQuery.getId();
        this.type = AnnotationQueryType.REGULAR.getName();
        this.setTumorType(mutationQuery.getTumorType());

        this.hgvs = mutationQuery.getHgvsg();
        this.referenceGenome = mutationQuery.getReferenceGenome();
        if (this.referenceGenome == null) {
            this.referenceGenome = DEFAULT_REFERENCE_GENOME;
        }
    }

    public Query(AnnotateStructuralVariantQuery svQuery) {
        this.id = svQuery.getId();
        this.type = AnnotationQueryType.REGULAR.getName();
        this.setTumorType(svQuery.getTumorType());

        this.referenceGenome = svQuery.getReferenceGenome();
        if (this.referenceGenome == null) {
            this.referenceGenome = DEFAULT_REFERENCE_GENOME;
        }
        this.hugoSymbol = resolveHugoSymbol(svQuery.getGeneA()) + "-" + resolveHugoSymbol(svQuery.getGeneB());

        this.alterationType = AlterationType.STRUCTURAL_VARIANT.name();
        this.svType = svQuery.getStructuralVariantType();
        this.consequence = svQuery.getFunctionalFusion() ? "fusion" : "";
    }

    private static String resolveHugoSymbol(QueryGene queryGene) {
        Gene gene = GeneUtils.getGene(queryGene.getEntrezGeneId(), queryGene.getHugoSymbol());
        String geneHugoSymbol = gene == null ? queryGene.getHugoSymbol() : gene.getHugoSymbol();
        if (com.mysql.jdbc.StringUtils.isNullOrEmpty(geneHugoSymbol)) {
            if (queryGene.getEntrezGeneId() != null) {
                gene = findGene(Integer.toString(queryGene.getEntrezGeneId()));
                geneHugoSymbol = gene.getHugoSymbol();
            }
            if (com.mysql.jdbc.StringUtils.isNullOrEmpty(geneHugoSymbol)) {
                geneHugoSymbol = "";
            }
        }
        return geneHugoSymbol;
    }

    public Query(AnnotateCopyNumberAlterationQuery cnaQuery) {
        this.id = cnaQuery.getId();
        this.type = AnnotationQueryType.REGULAR.getName();
        this.setTumorType(cnaQuery.getTumorType());

        this.hugoSymbol = resolveHugoSymbol(cnaQuery.getGene());
        this.referenceGenome = cnaQuery.getReferenceGenome();
        if (this.referenceGenome == null) {
            this.referenceGenome = DEFAULT_REFERENCE_GENOME;
        }

        setAlteration(StringUtils.capitalize(cnaQuery.getCopyNameAlterationType().name().toLowerCase()));
    }

    public Query(Alteration alt, ReferenceGenome referenceGenome) {
        if (alt != null) {
            if (alt.getGene() != null) {
                this.hugoSymbol = alt.getGene().getHugoSymbol();
                this.entrezGeneId = alt.getGene().getEntrezGeneId();
            }
            setAlteration(alt.getAlteration());
            this.alterationType = alt.getAlterationType() == null ? "MUTATION" : alt.getAlterationType().name();
            this.consequence = alt.getConsequence() == null ? null : alt.getConsequence().getTerm();
            this.proteinStart = alt.getProteinStart();
            this.proteinEnd = alt.getProteinEnd();
            this.referenceGenome = referenceGenome;
            if (this.referenceGenome == null) {
                this.referenceGenome = DEFAULT_REFERENCE_GENOME;
            }
        }
    }

    public Query(String hugoSymbol, String alteration, String tumorType) {
        this.hugoSymbol = hugoSymbol;
        this.setAlteration(alteration);
        this.setTumorType(tumorType);
    }

    public Query(String id, ReferenceGenome referenceGenome, String type, Integer entrezGeneId, String hugoSymbol,
                 String alteration, String alterationType, StructuralVariantType svType,
                 String tumorType, String consequence, Integer proteinStart, Integer proteinEnd, String hgvs) {
        this.id = id;
        this.referenceGenome = referenceGenome == null ? DEFAULT_REFERENCE_GENOME : referenceGenome;
        this.type = type;
        if (hugoSymbol != null && !hugoSymbol.isEmpty()) {
            this.hugoSymbol = hugoSymbol;
        }
        this.entrezGeneId = entrezGeneId;
        this.setAlteration(alteration);
        this.alterationType = alterationType;
        this.svType = svType;
        this.setTumorType(tumorType);
        this.consequence = consequence;
        this.proteinStart = proteinStart;
        this.proteinEnd = proteinEnd;
        this.setHgvs(hgvs, referenceGenome);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ReferenceGenome getReferenceGenome() {
        return referenceGenome;
    }

    public void setReferenceGenome(ReferenceGenome referenceGenome) {
        this.referenceGenome = referenceGenome;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getHugoSymbol() {
        return hugoSymbol;
    }

    public void setHugoSymbol(String hugoSymbol) {
        this.hugoSymbol = hugoSymbol;
    }

    public Integer getEntrezGeneId() {
        return entrezGeneId;
    }

    public void setEntrezGeneId(Integer entrezGeneId) {
        this.entrezGeneId = entrezGeneId;
    }

    public String getAlteration() {
        return alteration;
    }

    public void setAlteration(String alteration) {
        if (alteration != null) {
            alteration = alteration.replace("p.", "");
        }
        this.alteration = alteration;
    }

    public String getAlterationType() {
        return alterationType;
    }

    public void setAlterationType(String alterationType) {
        this.alterationType = alterationType;
    }

    public StructuralVariantType getSvType() {
        return svType;
    }

    public void setSvType(StructuralVariantType svType) {
        this.svType = svType;
    }

    public String getTumorType() {
        return tumorType;
    }

    public void setTumorType(String tumorType) {
        if (tumorType != null) {
            tumorType = tumorType.trim();
        }
        this.tumorType = tumorType;
    }

    public String getConsequence() {
        return consequence;
    }

    public void setConsequence(String consequence) {
        this.consequence = consequence;
    }

    public Integer getProteinStart() {
        return proteinStart;
    }

    public void setProteinStart(Integer proteinStart) {
        this.proteinStart = proteinStart;
    }

    public Integer getProteinEnd() {
        return proteinEnd;
    }

    public void setProteinEnd(Integer proteinEnd) {
        this.proteinEnd = proteinEnd;
    }

    public String getHgvs() {
        return hgvs;
    }

    public void setHgvs(String hgvs, ReferenceGenome referenceGenome) {
        this.hgvs = hgvs;
        if (hgvs != null && !hgvs.trim().isEmpty()) {
            Alteration alteration = AlterationUtils.getAlterationFromGenomeNexus(GNVariantAnnotationType.HGVS_G, hgvs, referenceGenome);
            if (alteration != null) {
                if (alteration.getGene() != null) {
                    this.hugoSymbol = alteration.getGene().getHugoSymbol();
                    this.entrezGeneId = alteration.getGene().getEntrezGeneId();
                }
                this.alterationType = null;
                this.setAlteration(alteration.getAlteration());
                this.proteinStart = alteration.getProteinStart();
                this.proteinEnd = alteration.getProteinEnd();
                if (alteration.getConsequence() != null)
                    this.consequence = alteration.getConsequence().getTerm();
            }
        }
    }

    public void enrich() {
        if (this.getEntrezGeneId() == null && this.getHugoSymbol() == null
            && this.getAlteration() != null && !this.getAlteration().isEmpty()) {
            this.setEntrezGeneId(-2);
        }

        // For structural variant, if the entrezGeneId is specified which means this is probably a intragenic event. In this case, the hugoSymbol should be ignore.
        if (this.getAlterationType() != null) {
            AlterationType alterationType = AlterationType.getByName(this.getAlterationType());
            if (alterationType != null && (alterationType.equals(AlterationType.FUSION) ||
                alterationType.equals(AlterationType.STRUCTURAL_VARIANT)) &&
                this.getEntrezGeneId() != null) {
                Gene entrezGeneIdGene = GeneUtils.getGeneByEntrezId(this.getEntrezGeneId());
                this.setHugoSymbol(entrezGeneIdGene.getHugoSymbol());
            }
            if (this.getAlteration() != null && !this.getAlteration().toLowerCase().contains("fusion") && this.getAlteration().toLowerCase().contains("-") && (alterationType.equals(AlterationType.FUSION) || (this.consequence != null && this.consequence.toLowerCase().equals("fusion")))) {
                this.setAlteration(this.getAlteration() + " Fusion");
            }
        }

        // Set the alteration to empty string in order to get relevant variants.
        if (this.getAlteration() == null) {
            this.setAlteration("");
        }

        this.setAlteration(QueryUtils.getAlterationName(this));
    }

    @JsonIgnore
    public String getQueryId() {

        List<String> content = new ArrayList<>();
        if (this.entrezGeneId != null) {
            content.add(Integer.toString(this.entrezGeneId));
        } else {
            if (this.hugoSymbol != null) {
                content.add(this.hugoSymbol);
            } else {
                content.add("");
            }
        }
        if (this.alteration != null) {
            content.add(this.alteration);
        } else {
            content.add("");
        }
        if (this.alterationType != null) {
            content.add(this.alterationType);
        } else {
            content.add("");
        }
        if (this.svType != null) {
            content.add(this.svType.name());
        } else {
            content.add("");
        }
        if (this.type != null) {
            content.add(this.type);
        } else {
            content.add("");
        }
        if (this.tumorType != null) {
            content.add(this.tumorType);
        } else {
            content.add("");
        }
        if (consequence != null) {
            content.add(this.consequence);
        } else {
            content.add("");
        }
        if (this.proteinStart != null) {
            content.add(Integer.toString(this.proteinStart));
        } else {
            content.add("");
        }

        if (this.proteinEnd != null) {
            content.add(Integer.toString(this.proteinEnd));
        } else {
            content.add("");
        }

        if (this.hgvs != null) {
            content.add(this.hgvs);
        } else {
            content.add("");
        }

        return StringUtils.join(content.toArray(), "&");
    }
}


