package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA

import java.util.List;


/**
 * TumorType generated by hbm2java
 */
public class SummaryQueries implements java.io.Serializable {
    private List<Query> queries; //Optional, This id is passed from request. The identifier used to distinguish the query
    private String type; //Summary type (variant, full)
    private String source;

    public SummaryQueries() {
    }

    public List<Query> getQueries() {
        return queries;
    }

    public void setQueries(List<Query> queries) {
        this.queries = queries;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}


