package org.mskcc.cbio.oncokb.model;


import java.util.List;


/**
 * TumorType generated by hbm2java
 */
public class SummaryQueryRes implements java.io.Serializable {
    private String id; //Optional, This id is passed from request. The identifier used to distinguish the query
    private String summary;

    public SummaryQueryRes() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }
}


