package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * TumorType generated by hbm2java
 */
public class TumorType implements java.io.Serializable {


     private String tumorTypeId;
     private String name;
     private String shortName;
     private String tissue;
     private Set<String> clinicalTrialKeywords = new HashSet<String>();

    public TumorType() {
    }
    
    public String getTumorTypeId() {
        return this.tumorTypeId;
    }
    
    
    public void setTumorTypeId(String tumorTypeId) {
        this.tumorTypeId = tumorTypeId;
    }
    
    public String getName() {
        return this.name;
    }
    
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getShortName() {
        return this.shortName;
    }
    
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    
    public String getTissue() {
        return this.tissue;
    }
    
    
    public void setTissue(String tissue) {
        this.tissue = tissue;
    }

    public Set<String> getClinicalTrialKeywords() {
        return clinicalTrialKeywords;
    }

    public void setClinicalTrialKeywords(Set<String> clinicalTrialKeywords) {
        this.clinicalTrialKeywords = clinicalTrialKeywords;
    }

    
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.tumorTypeId != null ? this.tumorTypeId.hashCode() : 0);
        return hash;
    }

    
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TumorType other = (TumorType) obj;
        if ((this.tumorTypeId == null) ? (other.tumorTypeId != null) : !this.tumorTypeId.equals(other.tumorTypeId)) {
            return false;
        }
        return true;
    }


}


