package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;



/**
 * Evidence generated by hbm2java
 */
public class Evidence implements java.io.Serializable {


     private Integer evidenceId;
     private String evidenceType;
     private TumorType tumorType;
     private Drug drug;
     private Alteration alteration;
     private String knownEffect;
     private String descriptionOfKnownEffect;
     private String context;
     private Set<String> pmids = new HashSet<String>(0);

    public Evidence() {
    }

	
    public Evidence(String evidenceType, Alteration alteration, String knownEffect) {
        this.evidenceType = evidenceType;
        this.alteration = alteration;
        this.knownEffect = knownEffect;
    }
    public Evidence(String evidenceType, TumorType tumorType, Drug drug, Alteration alteration, String knownEffect, String descriptionOfKnownEffect, String context, Set<String> pmids) {
        this.evidenceType = evidenceType;
        this.tumorType = tumorType;
        this.drug = drug;
        this.alteration = alteration;
        this.knownEffect = knownEffect;
        this.descriptionOfKnownEffect = descriptionOfKnownEffect;
        this.context = context;
        this.pmids = pmids;
    }
   
    
    public Integer getEvidenceId() {
        return this.evidenceId;
    }
    
    
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }

    public String getEvidenceType() {
        return evidenceType;
    }

    public void setEvidenceType(String evidenceType) {
        this.evidenceType = evidenceType;
    }
    
    public TumorType getTumorType() {
        return this.tumorType;
    }
    
    
    public void setTumorType(TumorType tumorType) {
        this.tumorType = tumorType;
    }
    
    public Drug getDrug() {
        return this.drug;
    }
    
    
    public void setDrug(Drug drug) {
        this.drug = drug;
    }
    
    public Alteration getAlteration() {
        return this.alteration;
    }
    
    
    public void setAlteration(Alteration alteration) {
        this.alteration = alteration;
    }
    
    public String getKnownEffect() {
        return this.knownEffect;
    }
    
    
    public void setKnownEffect(String knownEffect) {
        this.knownEffect = knownEffect;
    }
    
    public String getDescriptionOfKnownEffect() {
        return this.descriptionOfKnownEffect;
    }
    
    
    public void setDescriptionOfKnownEffect(String descriptionOfKnownEffect) {
        this.descriptionOfKnownEffect = descriptionOfKnownEffect;
    }
    
    public String getContext() {
        return this.context;
    }
    
    
    public void setContext(String context) {
        this.context = context;
    }
    
    public Set<String> getPmids() {
        return this.pmids;
    }
    
    
    public void setPmids(Set<String> pmids) {
        this.pmids = pmids;
    }




}


