package org.mskcc.cbio.oncokb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA



/**
 * TumorType generated by hbm2java
 */
public class TumorType implements java.io.Serializable {


     private String tumorTypeId;
     private String name;
     private String shortName;
     private String color;

    public TumorType() {
    }

	
    public TumorType(String tumorTypeId, String name, String shortName) {
        this.tumorTypeId = tumorTypeId;
        this.name = name;
        this.shortName = shortName;
    }
    public TumorType(String tumorTypeId, String name, String shortName, String color) {
       this.tumorTypeId = tumorTypeId;
       this.name = name;
       this.shortName = shortName;
       this.color = color;
    }
   
    
    public String getTumorTypeId() {
        return this.tumorTypeId;
    }
    
    
    public void setTumorTypeId(String tumorTypeId) {
        this.tumorTypeId = tumorTypeId;
    }
    
    public String getName() {
        return this.name;
    }
    
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getShortName() {
        return this.shortName;
    }
    
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    
    public String getColor() {
        return this.color;
    }
    
    
    public void setColor(String color) {
        this.color = color;
    }

    
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.tumorTypeId != null ? this.tumorTypeId.hashCode() : 0);
        return hash;
    }

    
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TumorType other = (TumorType) obj;
        if ((this.tumorTypeId == null) ? (other.tumorTypeId != null) : !this.tumorTypeId.equals(other.tumorTypeId)) {
            return false;
        }
        return true;
    }


}


