package org.mskcc.cbio.oncogkb.model;
// Generated Oct 31, 2013 4:28:42 PM by Hibernate Tools 3.2.1.GA



/**
 * Alteration generated by hbm2java
 */
public class Alteration  implements java.io.Serializable {


     private Integer alterationId;
     private Gene gene;
     private String alteration;
     private String type;

    public Alteration() {
    }

    public Alteration(Gene gene, String alteration, String type) {
       this.gene = gene;
       this.alteration = alteration;
       this.type = type;
    }
   
    public Integer getAlterationId() {
        return this.alterationId;
    }
    
    public void setAlterationId(Integer alterationId) {
        this.alterationId = alterationId;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getAlteration() {
        return this.alteration;
    }
    
    public void setAlteration(String alteration) {
        this.alteration = alteration;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


