package org.mskcc.cbio.oncogkb.model;
// Generated Dec 12, 2013 4:07:37 PM by Hibernate Tools 3.2.1.GA



/**
 * AlterationActivityEvidence generated by hbm2java
 */
public class AlterationActivityEvidence  implements java.io.Serializable {


     private Integer evidenceId;
     private TumorType tumorType;
     private Alteration alteration;
     private String conclusion;
     private String downstreamEffect;
     private String context;
     private String pmids;
     private String comments;

    public AlterationActivityEvidence() {
    }

	
    public AlterationActivityEvidence(Alteration alteration, String conclusion) {
        this.alteration = alteration;
        this.conclusion = conclusion;
    }
    public AlterationActivityEvidence(TumorType tumorType, Alteration alteration, String conclusion, String downstreamEffect, String context, String pmids, String comments) {
       this.tumorType = tumorType;
       this.alteration = alteration;
       this.conclusion = conclusion;
       this.downstreamEffect = downstreamEffect;
       this.context = context;
       this.pmids = pmids;
       this.comments = comments;
    }
   
    public Integer getEvidenceId() {
        return this.evidenceId;
    }
    
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }
    public TumorType getTumorType() {
        return this.tumorType;
    }
    
    public void setTumorType(TumorType tumorType) {
        this.tumorType = tumorType;
    }
    public Alteration getAlteration() {
        return this.alteration;
    }
    
    public void setAlteration(Alteration alteration) {
        this.alteration = alteration;
    }
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }
    public String getDownstreamEffect() {
        return this.downstreamEffect;
    }
    
    public void setDownstreamEffect(String downstreamEffect) {
        this.downstreamEffect = downstreamEffect;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public String getPmids() {
        return this.pmids;
    }
    
    public void setPmids(String pmids) {
        this.pmids = pmids;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


