package org.mskcc.cbio.oncogkb.model;
// Generated Dec 12, 2013 4:07:37 PM by Hibernate Tools 3.2.1.GA



/**
 * DrugSensitivityEvidence generated by hbm2java
 */
public class DrugSensitivityEvidence  implements java.io.Serializable {


     private Integer evidenceId;
     private TumorType tumorType;
     private Drug drug;
     private Alteration alteration;
     private String conclusion;
     private String context;
     private String pmids;
     private String comments;

    public DrugSensitivityEvidence() {
    }

	
    public DrugSensitivityEvidence(Alteration alteration, String conclusion) {
        this.alteration = alteration;
        this.conclusion = conclusion;
    }
    public DrugSensitivityEvidence(TumorType tumorType, Drug drug, Alteration alteration, String conclusion, String context, String pmids, String comments) {
       this.tumorType = tumorType;
       this.drug = drug;
       this.alteration = alteration;
       this.conclusion = conclusion;
       this.context = context;
       this.pmids = pmids;
       this.comments = comments;
    }
   
    public Integer getEvidenceId() {
        return this.evidenceId;
    }
    
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }
    public TumorType getTumorType() {
        return this.tumorType;
    }
    
    public void setTumorType(TumorType tumorType) {
        this.tumorType = tumorType;
    }
    public Drug getDrug() {
        return this.drug;
    }
    
    public void setDrug(Drug drug) {
        this.drug = drug;
    }
    public Alteration getAlteration() {
        return this.alteration;
    }
    
    public void setAlteration(Alteration alteration) {
        this.alteration = alteration;
    }
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public String getPmids() {
        return this.pmids;
    }
    
    public void setPmids(String pmids) {
        this.pmids = pmids;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


