package org.mskcc.cbio.oncogkb.model;
// Generated Oct 31, 2013 4:28:42 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Drug generated by hbm2java
 */
public class Drug  implements java.io.Serializable {


     private Integer drugId;
     private String drugName;
     private String synonyms;
     private boolean fdaApproved;
     private Set<Evidence> evidences = new HashSet<Evidence>(0);

    public Drug() {
    }

	
    public Drug(String drugName, boolean fdaApproved) {
        this.drugName = drugName;
        this.fdaApproved = fdaApproved;
    }
    public Drug(String drugName, String synonyms, boolean fdaApproved, Set<Evidence> evidences) {
       this.drugName = drugName;
       this.synonyms = synonyms;
       this.fdaApproved = fdaApproved;
       this.evidences = evidences;
    }
   
    public Integer getDrugId() {
        return this.drugId;
    }
    
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }
    public String getDrugName() {
        return this.drugName;
    }
    
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }
    public String getSynonyms() {
        return this.synonyms;
    }
    
    public void setSynonyms(String synonyms) {
        this.synonyms = synonyms;
    }
    public boolean isFdaApproved() {
        return this.fdaApproved;
    }
    
    public void setFdaApproved(boolean fdaApproved) {
        this.fdaApproved = fdaApproved;
    }
    public Set<Evidence> getEvidences() {
        return this.evidences;
    }
    
    public void setEvidences(Set<Evidence> evidences) {
        this.evidences = evidences;
    }




}


