package org.mskcc.cbio.oncogkb.model;
// Generated Oct 31, 2013 4:28:42 PM by Hibernate Tools 3.2.1.GA



/**
 * Evidence generated by hbm2java
 */
public class Evidence  implements java.io.Serializable {


     private Integer evidenceId;
     private TumorType tumorType;
     private Drug drug;
     private Gene gene;
     private String evidenceType;
     private String pmids;

    public Evidence() {
    }

	
    public Evidence(TumorType tumorType, Gene gene, String evidenceType) {
        this.tumorType = tumorType;
        this.gene = gene;
        this.evidenceType = evidenceType;
    }
    public Evidence(TumorType tumorType, Drug drug, Gene gene, String evidenceType, String pmids) {
       this.tumorType = tumorType;
       this.drug = drug;
       this.gene = gene;
       this.evidenceType = evidenceType;
       this.pmids = pmids;
    }
   
    public Integer getEvidenceId() {
        return this.evidenceId;
    }
    
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }
    public TumorType getTumorType() {
        return this.tumorType;
    }
    
    public void setTumorType(TumorType tumorType) {
        this.tumorType = tumorType;
    }
    public Drug getDrug() {
        return this.drug;
    }
    
    public void setDrug(Drug drug) {
        this.drug = drug;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getEvidenceType() {
        return this.evidenceType;
    }
    
    public void setEvidenceType(String evidenceType) {
        this.evidenceType = evidenceType;
    }
    public String getPmids() {
        return this.pmids;
    }
    
    public void setPmids(String pmids) {
        this.pmids = pmids;
    }




}


