package org.mskcc.cbio.oncogkb.model;
// Generated Dec 13, 2013 4:22:38 PM by Hibernate Tools 3.2.1.GA



/**
 * GeneLabel generated by hbm2java
 */
public class GeneLabel  implements java.io.Serializable {


     private Integer geneLabelId;
     private Gene gene;
     private String label;

    public GeneLabel() {
    }

    public GeneLabel(Gene gene, String label) {
       this.gene = gene;
       this.label = label;
    }
   
    public Integer getGeneLabelId() {
        return this.geneLabelId;
    }
    
    public void setGeneLabelId(Integer geneLabelId) {
        this.geneLabelId = geneLabelId;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }




}


