package org.mskcc.cbio.oncogkb.model;
// Generated Dec 12, 2013 4:07:37 PM by Hibernate Tools 3.2.1.GA



/**
 * GeneEvidence generated by hbm2java
 */
public class GeneEvidence  implements java.io.Serializable {


     private Integer evidenceId;
     private TumorType tumorType;
     private Gene gene;
     private String conclusion;
     private String pmids;
     private String comments;

    public GeneEvidence() {
    }

	
    public GeneEvidence(Gene gene, String conclusion) {
        this.gene = gene;
        this.conclusion = conclusion;
    }
    public GeneEvidence(TumorType tumorType, Gene gene, String conclusion, String pmids, String comments) {
       this.tumorType = tumorType;
       this.gene = gene;
       this.conclusion = conclusion;
       this.pmids = pmids;
       this.comments = comments;
    }
   
    public Integer getEvidenceId() {
        return this.evidenceId;
    }
    
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }
    public TumorType getTumorType() {
        return this.tumorType;
    }
    
    public void setTumorType(TumorType tumorType) {
        this.tumorType = tumorType;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }
    public String getPmids() {
        return this.pmids;
    }
    
    public void setPmids(String pmids) {
        this.pmids = pmids;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


