package org.mskcc.cbio.oncogkb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA



/**
 * GeneAlias generated by hbm2java
 */
public class GeneAlias  implements java.io.Serializable {


     private Integer geneAliasId;
     private Gene gene;
     private String alias;

    public GeneAlias() {
    }

    public GeneAlias(Gene gene, String alias) {
       this.gene = gene;
       this.alias = alias;
    }
   
    public Integer getGeneAliasId() {
        return this.geneAliasId;
    }
    
    public void setGeneAliasId(Integer geneAliasId) {
        this.geneAliasId = geneAliasId;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + (this.gene != null ? this.gene.hashCode() : 0);
        hash = 23 * hash + (this.alias != null ? this.alias.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GeneAlias other = (GeneAlias) obj;
        if (this.gene != other.gene && (this.gene == null || !this.gene.equals(other.gene))) {
            return false;
        }
        if ((this.alias == null) ? (other.alias != null) : !this.alias.equals(other.alias)) {
            return false;
        }
        return true;
    }

}


