package org.mskcc.cbio.oncogkb.model;
// Generated Dec 19, 2013 1:33:26 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Gene generated by hbm2java
 */
public class Gene  implements java.io.Serializable {


     private int entrezGeneId;
     private String hugoSymbol;
     private String name;
     private String summary;
     private Set<Alteration> alterations = new HashSet<Alteration>(0);
     private Set<GeneLabel> geneLabels = new HashSet<GeneLabel>(0);
     private Set<GeneAlias> geneAliases = new HashSet<GeneAlias>(0);

    public Gene() {
    }

	
    public Gene(int entrezGeneId, String hugoSymbol, String name) {
        this.entrezGeneId = entrezGeneId;
        this.hugoSymbol = hugoSymbol;
        this.name = name;
    }
    public Gene(int entrezGeneId, String hugoSymbol, String name, String summary, Set<Alteration> alterations, Set<GeneLabel> geneLabels, Set<GeneAlias> geneAliases) {
       this.entrezGeneId = entrezGeneId;
       this.hugoSymbol = hugoSymbol;
       this.name = name;
       this.summary = summary;
       this.alterations = alterations;
       this.geneLabels = geneLabels;
       this.geneAliases = geneAliases;
    }
   
    public int getEntrezGeneId() {
        return this.entrezGeneId;
    }
    
    public void setEntrezGeneId(int entrezGeneId) {
        this.entrezGeneId = entrezGeneId;
    }
    public String getHugoSymbol() {
        return this.hugoSymbol;
    }
    
    public void setHugoSymbol(String hugoSymbol) {
        this.hugoSymbol = hugoSymbol;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public Set<Alteration> getAlterations() {
        return this.alterations;
    }
    
    public void setAlterations(Set<Alteration> alterations) {
        this.alterations = alterations;
    }
    public Set<GeneLabel> getGeneLabels() {
        return this.geneLabels;
    }
    
    public void setGeneLabels(Set<GeneLabel> geneLabels) {
        this.geneLabels = geneLabels;
    }
    public Set<GeneAlias> getGeneAliases() {
        return this.geneAliases;
    }
    
    public void setGeneAliases(Set<GeneAlias> geneAliases) {
        this.geneAliases = geneAliases;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + this.entrezGeneId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Gene other = (Gene) obj;
        if (this.entrezGeneId != other.entrezGeneId) {
            return false;
        }
        return true;
    }


}


