package org.mskcc.cbio.oncogkb.model;
// Generated Dec 19, 2013 12:58:26 AM by Hibernate Tools 3.2.1.GA



/**
 * GeneLabel generated by hbm2java
 */
public class GeneLabel  implements java.io.Serializable {


     private Integer geneLabelId;
     private Gene gene;
     private String label;

    public GeneLabel() {
    }

    public GeneLabel(Gene gene, String label) {
       this.gene = gene;
       this.label = label;
    }
   
    public Integer getGeneLabelId() {
        return this.geneLabelId;
    }
    
    public void setGeneLabelId(Integer geneLabelId) {
        this.geneLabelId = geneLabelId;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GeneLabel other = (GeneLabel) obj;
        if (this.gene != other.gene && (this.gene == null || !this.gene.equals(other.gene))) {
            return false;
        }
        if ((this.label == null) ? (other.label != null) : !this.label.equals(other.label)) {
            return false;
        }
        return true;
    }


}


