package org.mskcc.cbio.oncogkb.model;
// Generated Dec 18, 2013 3:43:05 PM by Hibernate Tools 3.2.1.GA



/**
 * GeneAlias generated by hbm2java
 */
public class GeneAlias  implements java.io.Serializable {


     private Integer geneAliasId;
     private Gene gene;
     private String aliase;

    public GeneAlias() {
    }

    public GeneAlias(Gene gene, String aliase) {
       this.gene = gene;
       this.aliase = aliase;
    }
   
    public Integer getGeneAliasId() {
        return this.geneAliasId;
    }
    
    public void setGeneAliasId(Integer geneAliasId) {
        this.geneAliasId = geneAliasId;
    }
    public Gene getGene() {
        return this.gene;
    }
    
    public void setGene(Gene gene) {
        this.gene = gene;
    }
    public String getAliase() {
        return this.aliase;
    }
    
    public void setAliase(String aliase) {
        this.aliase = aliase;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GeneAlias other = (GeneAlias) obj;
        if (this.gene != other.gene && (this.gene == null || !this.gene.equals(other.gene))) {
            return false;
        }
        if ((this.aliase == null) ? (other.aliase != null) : !this.aliase.equals(other.aliase)) {
            return false;
        }
        return true;
    }

}


